name: Unit Tests

on: [push, pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest pytest-cov pytest-html
            - name: Run Unit Tests
              run: python3 -m pytest --cov-report=xml --cov=. --html=report.html -v

            - name: Export Unit Tests Artifact
              uses: actions/upload-artifact@v2
              with:
                name: unit-tests-report
                path: ./report.html
